export const COLOR_PRIMARY = "#17494D"; //green
export const COLOR_SECONDARY = "#0E2C2E"; // black
export const COLOR_INPUT_BG = "#E5E5E7"; //light gray
export const COLOR_MENU_TEXT = "#E5E5E7"; //light gray
export const COLOR_HOVER_PRIMARY = "#323539"; //light black
export const COLOR_HOVER_SECONDARY = "#858C95"; //gray
export const COLOR_TEXT_PRIMARY = "#323539"; //light black
export const COLOR_TEXT_SECONDARY = "#858C95"; //gray
export const AUTH_PAGE_BG = "#f8f9fb"; //gray
export const COLOR_ERROR = "#C8322B"; //red
export const COLOR_SUCCESS = "#2AA63C"; //green
export const COLOR_WHITE = "#ffffff"; //white
export const COLOR_LOADER_BG = "#E3EBEB"; //ash
export const COLOR_CUSTOM_PURPLE = "#33059F";
export const COLOR_LIGHT_PURPLE = "#F9F8FB";
export const COLOR_LIGHT_GREEN = "#F3FFF6";
export const COLOR_LIGHT_RED = "#FFEFEE";
export const COLOR_DISABLED = "#9599A1";
export const COLOR_BORDER = "#E5E5E7";
export const COLOR_WARN = "#D78100";

export const COLOR_AVAILABLE_STATUS_COLOR = "#2AA63C";
export const COLOR_AVAILABLE_STATUS_BG_COLOR = "#F3FFF6";
export const COLOR_DOWN_STATUS_COLOR = "#EEA23E";
export const COLOR_DOWN_STATUS_BG_COLOR = "#FFFAF2";
export const COLOR_IN_USE_STATUS_COLOR = "#463EE3";
export const COLOR_IN_USE_STATUS_BG_COLOR = "#463EE3";
export const COLOR_RESTRICTED_STATUS_COLOR = "#323539";
export const COLOR_RESTRICTED_STATUS_BG_COLOR = "#F8F9FB";
export const COLOR_OFFLINE_STATUS_COLOR = "#C8322B";
export const COLOR_OFFLINE_STATUS_BG_COLOR = "#FFEFEE";
